set timeout 160
spawn /usr/bin/ssh  [lindex $argv 0]@[lindex $argv 1]
expect "$ "
send "git clone https://github.com/openstack-dev/devstack\r"
expect "$ "
send "touch devstack/localrc\r"
expect "$ "
send "echo \"ADMIN_PASSWORD=111\" >> devstack/localrc\r"
expect "$ "
send "echo \"MYSQL_PASSWORD=111\" >> devstack/localrc\r"
expect "$ "
send "echo \"RABBIT_PASSWORD=111\" >> devstack/localrc\r"
expect "$ "
send "echo \"SERVICE_PASSWORD=111\" >> devstack/localrc\r"
expect "$ "
send "echo \"SERVICE_TOKEN=111\" >> devstack/localrc\r"
expect "$ "
send "echo \"disable_service n-net\" >> devstack/localrc\r"
expect "$ "
send "echo \"enable_service q-svc\" >> devstack/localrc\r"
expect "$ "
send "echo \"enable_service q-agt\" >> devstack/localrc\r"
expect "$ "
send "echo \"enable_service q-dhcp\" >> devstack/localrc\r"
expect "$ "
send "echo \"enable_service q-l3\" >> devstack/localrc\r"
expect "$ "
send "echo \"enable_service q-meta\" >> devstack/localrc\r"
expect "$ "
send "echo \"enable_service q-metering\" >> devstack/localrc\r"
expect "$ "
send "cd devstack\r"
expect "$ "
set timeout 2000
send "./stack.sh\r"
expect "$ "
send "exit\r"

